subdir-ccflags-y := -Werror
obj-m := rda_combo_power_ctrl.o
rda_combo_power_ctrl-objs := \
	rda_combo_power_main.o \
	rda_5990_power_ctrl.o \
	rda_5991_power_ctrl.o \
	rda_5991e_power_ctrl.o \
	rda_5991f_power_ctrl.o
