
# charger
obj-y += charger/g2214/
obj-y += charger/mp2625/

# gauge
obj-y += gauge/vt1603/
obj-y += gauge/ug31xx/
obj-y += gauge/sp2541/
obj-y += gauge/bq27xx/
obj-y += gauge/saradc/

# core
obj-y += wmt_battery.o

