obj-m := rda_wlan.o
rda_wlan-objs := \
	wlan_module.o \
	wlan_init.o \
	wlan_rxtx.o \
	wlan_wid.o \
	wlan_wext.o \
	wlan_sdio_patch.o \
	wlan_nvram.o \
	wlan_scan.o \
	wlan_assoc.o \
	wlan_sdio.o \
	wlan_event.o\
	wlan_debugfs.o\
	wlan_aver_rssi.o

subdir-ccflags-y := -Werror
